development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:f7c739208bbd849ed89d23a59febb24e@koi.redistogo.com:10190/
  channel_prefix: instagram_production
